### ISSUE TITLE
v0.0.8 checklist

### ISSUE THREAD

**Issue by mbrlabs** [mbrlabs/Mundus#7]
- [x] Refactor entity component system
- [x] Write unit tests for the scene graph
- [ ] Fix relative transformation of scene graph objects
- [x] Implement game object scaling (just scaling, the tool comes later)
